services:
  gateway:
    build:
      context: ./gateway
    ports:
      - 3001:3001
    environment:
      - IMAGE_SERVICE_PORT = 'https://localhost:3002'
      - MESSAGE_SERVICE_PORT = 'https://localhost:3003'
      - PORT = '3001'
    depends_on:
      - mongo-express
      - rabbitmq
  imageservice:
    build:
      context: ./imageService
    ports:
      - 3002:3002
    environment:
      - DB_URL = 'mongodb://localhost:27017/imageService'
      - RABBIT_URL = 'amqp://localhost:5672'
      - PORT = '3002'
    depends_on:
      - mongo-express
      - rabbitmq
  messageservice:
    build:
      context: ./messageService
    ports:
      - 3003:3003
    environment:
      - DB_URL = 'mongodb://localhost:27017/messageService'
      - RABBIT_URL = 'amqp://localhost:5672'
      - PORT = '3003'
    depends_on:
      - mongo-express
      - rabbitmq
  mongo-express:
    image: mongo
    container_name: mongo
    hostname: "mongo"
    restart: always
    ports:
      - 6942:27017
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    hostname: "rabbitmq"
    ports:
      - 5672:5672
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus
    hostname: "prometheus"
    ports:
      - 9090:9090
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
  grafana:
    build: ./grafana
    ports:
      - 1234:3000   
    depends_on:
      - prometheus