global:
  scrape_interval: 10s
  evaluation_interval: 10s
  scrape_timeout: 10s

#rule_files:
#  - alert.yml

scrape_configs:
  - job_name: "gateway"
    static_configs:
      - targets: [ "gateway:3001" ]
  - job_name: "imageService"
    static_configs:
      - targets: [ "imageService:3002" ]
  - job_name: "messageService"
    static_configs:
      - targets: [ "messageService:3003" ]